package com.compiler.utils;

public enum Token {
    PLUS, MINUS, DIVIDE, TIMES,
    GREATER, LESS, GREATER_EQUAL, LESS_EQUAL, EQUAL, NOT_EQUAL,
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, SEMICOLON, ASSIGN, QUOTE, COMMA,
    IDENTIFIER, NUMBER, FRACTION, STRING_VALUE,
    ERROR,
    RW,
}
